# Virtual Hosts
#
<VirtualHost _default_:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot "${INSTALL_DIR}/www"
  <Directory "${INSTALL_DIR}/www/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName blogart26.local
  ServerAlias blogart26.local
  DocumentRoot "c:/wamp64/www/blogart26"
  <Directory "c:/wamp64/www/blogart26/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName sleepers.local
  ServerAlias sleepers.local
  DocumentRoot "c:/wamp64/www/sleepers"
  <Directory "c:/wamp64/www/sleepers/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>